[package]
name = "fibonacci_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "fibonacci_rust"
crate-type = ["cdylib"]
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.15", features = ["extension-module"] }
